"""Initial migration

Revision ID: 1de6cbc49648
Revises: 
Create Date: 2026-06-30 23:15:06.334659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1de6cbc49648'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('auth', 'login',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('auth', 'password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('plat', 'nom',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('restaurant', 'nom',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('restaurant', 'auth_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('restaurant', 'auth_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('restaurant', 'nom',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('plat', 'nom',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('auth', 'password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('auth', 'login',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    # ### end Alembic commands ###
