"""empty message

Revision ID: 64befa558f81
Revises: 15983f92999d
Create Date: 2026-07-04 02:52:19.874184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64befa558f81'
down_revision: Union[str, Sequence[str], None] = '15983f92999d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('allergeneingredient', sa.Column('id_plat', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'allergeneingredient', 'plat', ['id_plat'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'allergeneingredient', type_='foreignkey')
    op.drop_column('allergeneingredient', 'id_plat')
    # ### end Alembic commands ###
